# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  backend:
    build: ./
    image: 63070104/img-backend:1.0
    ports: 
      - 8088:80
    networks:
      - back-tier

  frontend:
    build: ./frontend
    image: 63070104/img-frontend:1.0
    ports: 
      - 3000:3000
    links:
      - backend
    networks:
      - front-tier

networks:
  front-tier:
  back-tier: